source "https://rubygems.org"

gem "jekyll", "~> 4.3.3"
gem "github-pages", group: :jekyll_plugins
gem "jekyll-remote-theme"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "webrick" # Notwendig für Ruby 3.0+